### PR TITLE
Fix URLs.

### PR DESCRIPTION
**Pull request by danhper**
I wanted to add a link to last year Battlehack, and then I was sad :cry: 
screenshot-1462345362

I wrote a short script to add the base tag and use relative URLs.
It seems to be working pretty much ok, only the "axis-font" did not get fixed.
http://tuvistavie.github.io/2015.battlehack.org/

It would be nice if you could merge, thanks :smile:

### CODE REVIEW

**Comment by cbetta** [comment]
Uh, this site is live on 2015.battlehack.org. Not on the site you changed it to.

**Comment by danhper** [comment]
@cbetta https://2015.battlehack.org/tokyo redirects to http://braintreedev.github.io/2015.battlehack.org/tokyo/, so no way to have the page right now.

**Comment by cbetta** [comment]
Ah ok, well that's a different bug there :)

**Comment by danhper** [comment]
Ok, I thought you were moving things to github pages!
I'll close this PR then, thank you!

**Pull request closed without merging**
